Update README.md
XPRIZE/GLEXP-Team-KitkitSchool pull request #27
Opened 2019-07-02 21:12 UTC by todoschool

2019-07-09 19:14 UTC, jo-xprize requested changes

2019-07-09 19:14 UTC, jo-xprize commented on README.md
> +Kitkit School, name and logo, and Enuma are trademarks of Enuma, Inc. The Apache License 2.0 under which Kitkit School software is released does not grant any license or right to use the trademarks.
@todoschool Hyperlink missing?

2019-07-09 19:14 UTC, jo-xprize commented on README.md
> +<br>
@todoschool HTML formatting does not work, as this is a Markdown document. (See https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

2019-07-10 09:19 UTC, jo-xprize approved these changes

2019-07-10 09:20 UTC, GlobalLearningXPRIZE approved these changes

2019-07-17 18:28 UTC, jo-xprize commented on README.md
> +Kitkit School, name and logo, and Enuma are trademarks of Enuma, Inc. The Apache License 2.0 under which Kitkit School software is released does not grant any license or right to use the trademarks.
@todoschool Can you include the logo here so that people will know what it looks like?

2019-08-14 05:30 UTC, merged